"""add_missing_user_columns

Revision ID: 9d596bbe2a92
Revises: eb85b76fe7d1
Create Date: 2026-01-08 02:59:44.938164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d596bbe2a92'
down_revision = 'eb85b76fe7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Add missing CUSTOMER columns
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_zone_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('technician_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('connection_commission_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_foreign_key(None, 'sub_zones', ['sub_zone_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['technician_id'], ['id'])

    # 2. Add missing EXPENSE/INCOME columns
    with op.batch_alter_table('expense_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_employee_payment', sa.Boolean(), nullable=True))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('payment_proof', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['employee_id'], ['id'])

    with op.batch_alter_table('extra_incomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_proof', sa.String(length=500), nullable=True))

    # 3. Add missing RECOVERY TASK columns
    with op.batch_alter_table('recovery_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('completion_proof', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True))

    # 4. Add missing SERVICE PLAN columns
    with op.batch_alter_table('service_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isp_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'isps', ['isp_id'], ['id'])

    # 5. Add missing TASK columns
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('completion_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('completion_proof', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('completion_proof')
        batch_op.drop_column('completion_notes')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('service_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('isp_id')

    with op.batch_alter_table('recovery_tasks', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('completion_proof')
        batch_op.drop_column('completion_notes')

    with op.batch_alter_table('extra_incomes', schema=None) as batch_op:
        batch_op.drop_column('payment_proof')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('payment_proof')
        batch_op.drop_column('employee_id')

    with op.batch_alter_table('expense_types', schema=None) as batch_op:
        batch_op.drop_column('is_employee_payment')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('connection_commission_amount')
        batch_op.drop_column('technician_id')
        batch_op.drop_column('sub_zone_id')

    # ### end Alembic commands ###

    # ### end Alembic commands ###
