"""add_missing_user_columns

Revision ID: eb85b76fe7d1
Revises: b4a0eb84caa3
Create Date: 2026-01-08 02:46:38.689427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb85b76fe7d1'
down_revision = 'b4a0eb84caa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add current_balance to bank_accounts (Found missing in previous inspection)
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True))
    
    # 2. Add missing columns to users (The original cause of the crash)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_balance', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('commission_amount_per_complaint', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('commission_amount_per_complaint')
        batch_op.drop_column('paid_amount')
        batch_op.drop_column('current_balance')
        
    with op.batch_alter_table('bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('current_balance')

    # ### end Alembic commands ###

    # ### end Alembic commands ###
